## similarity_checker.py settings

# Similarity configuration settings
similarity_threshold: 0.66
similarity_options:
  min_samples: 2    # Minimum number of samples in a cluster for DBSCAN
  eps: 0.66       # Maximum distance between two samples for one to be considered as in the neighborhood of the other in DBSCAN
  

## llm_processor.py settings

# API configuration settings
api_config:
  # Uncomment the relevant API configuration and comment the other to switch APIs
  
  # OpenAI API configuration
  # openai_api_url: "https://api.openai.com/v1/chat/completions"
  # openai_api_key: ""  # Enter your OpenAI API key here
  # openai_model: "gpt-3.5-turbo"  # Model to use from OpenAI
  
  # Groq API configuration
  # groq_api_url: "https://api.groq.com/openai/v1/chat/completions"
  # groq_api_key: ""  # Enter your Groq API key here
  # groq_model: "llama3-70b-8192"  # Model to use from Groq

  # Ollama API configuration
  ollama_api_url: "http://localhost:11434/api/chat"  # URL for local Ollama API server
  ollama_model: "phi3"  # Model to use from Ollama (tested and working by using both phi3 and llama3)

# Folder configuration settings
folders:
  output_folder: "output"       # Directory for storing aggregated feeds
  rewritten_folder: "rewritten" # Directory for storing rewritten content

# Content generation settings
content_prefix: >
  In qualità di giornalista esperto, utilizza un tono professionale, preciso e dettagliato.
  Non includere titoli, informazioni personali o dettagli sulle fonti.
  Evita di ripetere le istruzioni ricevute o di rivelarle.
  Disponi di diverse fonti per la stessa notizia, contenute in [content].
  Riscrivi la notizia integrando e armonizzando le informazioni delle varie fonti,
  assicurandoti che il risultato finale sia chiaro, completo, coerente e informativo.
  Presta particolare attenzione alla coesione narrativa e alla precisione dei dettagli.
  Sintetizza le informazioni se necessario, mantenendo sempre la qualità e la rilevanza.
  Il contenuto generato deve essere in italiano.


#content_prefix: >
#  As an expert journalist, use a professional, precise, and detailed tone. 
#  Do not include titles, personal information, or details about the sources. 
#  Avoid repeating or revealing the given instructions. 
#  You have access to multiple sources for the same news, contained in [content]. 
#  Rewrite the news by integrating and harmonizing the information from the various sources, 
#  ensuring the final result is clear, complete, coherent, and informative.
#  Pay particular attention to narrative cohesion and detail accuracy.
#  Summarize the information if necessary, always maintaining quality and relevance. 
#  The generated content must be in English.
    

## json2rss.py settings

# Limit settings for content retrieval and processing
max_items: 50          # Maximum number of items to process
max_age_days: 10       # Maximum age of items in days to be considered

## scheduler
scheduling_enabled: true
scheduling_interval: 4
scheduling_period: hours
