services:
  uglyfeed: # Defines a service named 'uglyfeed'.
    build:
      context: . # Build from current directory
      dockerfile: Dockerfile # Use the Dockerfile in current directory
    # image: fabriziosalmi/uglyfeed:latest # Commented out - using local build instead
    ports:
      - "8001:8001" # Maps port 8001 on the host to port 8001 in the container.
      - "8501:8501" # Maps port 8501 on the host to port 8501 in the container.
    volumes:
      - ./input/feeds.txt:/app/input/feeds.txt # Mounts the local file 'feeds.txt' to '/app/input/feeds.txt' in the container.
      - ./config.yaml:/app/config.yaml # Mounts the local file 'config.yaml' to '/app/config.yaml' in the container.
      - ./output:/app/output # Mount output directory
      - ./rewritten:/app/rewritten # Mount rewritten directory
    environment:
      - PYTHONPATH=/app
    container_name: uglyfeed # Sets the container's name to 'uglyfeed' for easier identification and management.
    networks:
      - uglyfeed_network # Connects the service to the specified network 'uglyfeed_network'.

# Defines networks to be used by the services.
networks:
  uglyfeed_network: # This network will be used by the 'uglyfeed' service.
    name: uglyfeed_network
    driver: bridge # Use bridge driver for local development
