name: Deploy releses (GitHub, Pypi, DockerHub)

on:
  push:
    branches:
      - main
    paths:
      - 'setup.py'
      - 'requirements.txt'
      - 'config.py'
      - 'Dockerfile'
      - '.github/workflows/release.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install setuptools wheel twine

      - name: Extract version number from setup.py
        id: get_version
        run: |
          VERSION=$(python -c "import re; version_line = next(line for line in open('setup.py') if line.startswith('    version=')); print(re.search(r'[\"\\\']([^\"\\\']+)[\"\\\']', version_line).group(1))")
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Build package
        run: python setup.py sdist bdist_wheel

      - name: Publish to Test PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
        run: |
          twine upload --repository-url https://test.pypi.org/legacy/ dist/*

      - name: Verify installation from Test PyPI
        run: |
          pip install --index-url https://test.pypi.org/simple/ uglypy --extra-index-url https://pypi.org/simple

      - name: Publish package to PyPI
        if: |
          github.event_name == 'push' &&
          github.ref == 'refs/heads/main' &&
          !contains(github.event.head_commit.message, 'pylint') &&
          !contains(github.event.head_commit.message, 'dependabot') &&
          !contains(github.event.head_commit.message, 'CodeQL') &&
          !contains(github.event.head_commit.message, 'chore') &&
          !contains(github.event.head_commit.message, 'ci')
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          twine upload dist/*

      - name: Build and push Docker image
        if: |
          github.event_name == 'push' &&
          github.ref == 'refs/heads/main' &&
          !contains(github.event.head_commit.message, 'pylint') &&
          !contains(github.event.head_commit.message, 'dependabot') &&
          !contains(github.event.head_commit.message, 'CodeQL') &&
          !contains(github.event.head_commit.message, 'chore') &&
          !contains(github.event.head_commit.message, 'ci')
        run: |
          docker build -t fabriziosalmi/uglyfeed:${{ env.VERSION }} .
          docker tag fabriziosalmi/uglyfeed:${{ env.VERSION }} fabriziosalmi/uglyfeed:latest
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push fabriziosalmi/uglyfeed:${{ env.VERSION }}
          docker push fabriziosalmi/uglyfeed:latest

      - name: Create GitHub Release
        if: |
          github.event_name == 'push' &&
          github.ref == 'refs/heads/main' &&
          !contains(github.event.head_commit.message, 'pylint') &&
          !contains(github.event.head_commit.message, 'dependabot') &&
          !contains(github.event.head_commit.message, 'CodeQL') &&
          !contains(github.event.head_commit.message, 'chore') &&
          !contains(github.event.head_commit.message, 'ci')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: v${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          body: |
            ## Changes in this Release
            - Automatically generated release based on the following commit: ${{ github.sha }}
            - Commit message: ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false

      - name: Upload Release Asset (Optional)
        if: |
          steps.create_release.outputs.upload_url != '' &&
          !contains(github.event.head_commit.message, 'pylint') &&
          !contains(github.event.head_commit.message, 'dependabot') &&
          !contains(github.event.head_commit.message, 'CodeQL') &&
          !contains(github.event.head_commit.message, 'chore') &&
          !contains(github.event.head_commit.message, 'ci')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/*.whl
          asset_name: uglypy-${{ env.VERSION }}.whl
          asset_content_type: application/zip
